WIP/Added linting, PR check

diff --git a/.github/workflows/generate-html.yaml b/.github/workflows/generate-html.yaml
--- a/.github/workflows/generate-html.yaml
+++ b/.github/workflows/generate-html.yaml
@@ -4,7 +4,7 @@ on:
   pull_request:
     paths:
       - '**.md'
-      - 'scripts/convert-markdown.py'
+      - 'scripts/convert_markdown.py'
       - 'template.html'
   workflow_dispatch:
 
@@ -21,7 +21,92 @@ jobs:
       - name: Convert Markdown to html
         run: |
           pip3 install -r requirements.txt
-          python3 scripts/convert-markdown.py 
+          python3 scripts/convert_markdown.py 
+
+name: Branch CI
+
+on:
+  push:
+    branches:
+      - '*'
+      - '!main'
+env:
+  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
+  API_SERVER: "http://localhost:5000"
+  DB_SERVER: "${{ secrets.DB_SERVER }}"
+  DB_USER: "${{ secrets.DB_USER }}"
+  DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
+  DB_DATABASE: "${{ secrets.DB_DATABASE }}"
+jobs:
+  check-pr-ready:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch_depth: 0
+      - run: |
+          commit_message=$(git log -1 --pretty=format:"%s")
+          if [[ $commit_message == "WIP/"* ]]; then
+            echo "Not ready to PR yet"
+            exit 0
+          elif [[ $commit_message == "PR/"* ]]; then
+            echo "Ready to create PR!"
+            echo CREATE_PR=true >> $GITHUB_ENV
+            echo SEMVER_BUMP=$(echo $commit_message | awk -F'[\\[\\]]' '{print $2}') >> $GITHUB_ENV
+            echo COMMIT_MESSAGE=$(echo $commit_message | awk -F'[\\/\\[]' '{print $2}') >> $GITHUB_ENV
+            exit 0
+          else
+            echo "Commit message not in required format"
+            exit 1
+          fi
+      - name: Create Pull Request
+        if: env.CREATE_PR == 'true'
+        uses: actions/github-script@v6
+        with:
+          script: |
+            try {
+              const { repo, owner } = context.repo;
+              const result = await github.rest.pulls.create({
+                title: 'Merge ${{ github.ref_name }}',
+                owner,
+                repo,
+                head: '${{ github.ref_name }}',
+                base: 'main',
+                body: [
+                  '${{ env.COMMIT_MESSAGE }}'
+                ].join('\n')
+              })
+              github.rest.issues.addLabels({
+                owner,
+                repo,
+                issue_number: result.data.number,
+                labels: ['${{ env.SEMVER_BUMP }}']
+              });
+            } catch(error) {
+                error_message = error.message
+                if (error_message.includes("already exists")) {
+                  console.log("PR already exists, nothing to do")
+                } else {
+                  console.error(`Something has gone wrong ${error_message}`) 
+                }
+            }
+
+  unit-tests:
+    runs-on: self-hosted
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch_depth: 0
+      - name: Python linting
+        run: |
+          pip3 install isort pylint black
+          python3 -m isort ./scripts/convert_markdown.py
+          /usr/local/bin/black ./scripts/convert_markdown.py
+          /usr/local/bin/pylint --fail-under=9.9 ./scripts/convert_markdown.py
+      - name: Commit linted files
+        uses: stefanzweifel/git-auto-commit-action@v4
+        with:
+          commit_message: Linted and formatted files
       - name: Commit Pages docs
         uses: stefanzweifel/git-auto-commit-action@v4
         with: 
